### DISCUSSION TITLE
OpenHab connection and setup

### DISCUSSION THREAD

**Discussion by hubaksis** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#171] [Show and tell]
Just if you need a quick setup and connection with OpenHab - you can start with this.

.things file (MQTT base topic is set to 'spa_control' for the WiFi module)
```
Thing mqtt:topic:SpaControl "Spa control" (mqtt:broker:OpenhabianMQTT) @ "Outside" {
    Channels:
      Type switch : PowerChannel   [stateTopic="spa_control/message", on="1", off="0", transformationPattern="JSONPATH:$.PWR"] 
      Type switch : BubblesChannel   [stateTopic="spa_control/message",   commandTopic="spa_control/command", on="1", off="0", transformationPattern="JSONPATH:$.AIR", formatBeforePublish="{\"CMD\":2,\"VALUE\":%s,\"XTIME\":0,\"INTERVAL\":0}" ] 
      Type number : CurrentTemperatureChannel   [stateTopic="spa_control/message", transformationPattern="JSONPATH:$.TMP"] 
      Type number : TargetTemperatureChannel    [stateTopic="spa_control/message",   commandTopic="spa_control/command", transformationPattern="JSONPATH:$.TGT", formatBeforePublish="{\"CMD\":0,\"VALUE\":%s,\"XTIME\":0,\"INTERVAL\":0}" ] 
      Type switch : PumpChannel [stateTopic="spa_control/message",   commandTopic="spa_control/command", on="1", off="0", transformationPattern="JSONPATH:$.FLT", formatBeforePublish="{\"CMD\":4,\"VALUE\":%s,\"XTIME\":0,\"INTERVAL\":0}" ] 

      Type switch : HeaterRedChannel   [stateTopic="spa_control/message", on="1", off="0", transformationPattern="JSONPATH:$.RED" ]
      Type switch : HeaterGreenChannel [stateTopic="spa_control/message", on="1", off="0", transformationPattern="JSONPATH:$.GRN" ]
      Type switch : HeaterControlChannel [ commandTopic="spa_control/command", on="1", off="0", formatBeforePublish="{\"CMD\":3,\"VALUE\":%s,\"XTIME\":0,\"INTERVAL\":0}" ]      

      Type number : DisplayChar1 [stateTopic="spa_control/message", transformationPattern="JSONPATH:$.CH1" ]
      Type number : DisplayChar2 [stateTopic="spa_control/message", transformationPattern="JSONPATH:$.CH2" ]
      Type number : DisplayChar3 [stateTopic="spa_control/message", transformationPattern="JSONPATH:$.CH3" ]
}
```

.items
```
Switch SpaPower "Spa Power" { channel="mqtt:topic:SpaControl:PowerChannel" }

Switch SpaBubbles "Spa Bubbles" { channel="mqtt:topic:SpaControl:BubblesChannel" }
Number SpaCurrentTemperature "Current Temperature" (g_LastUpdatebleDate) { channel="mqtt:topic:SpaControl:CurrentTemperatureChannel" }
DateTime SpaCurrentTemperature_LastUpdate "[%1$td-%1$tm-%1$ty %1$ta %1$tT]"

Number SpaTargetTemperature "Target Temperature [%.0f]" { channel="mqtt:topic:SpaControl:TargetTemperatureChannel" }

Switch SpaPump "Spa pump" { channel="mqtt:topic:SpaControl:PumpChannel" }

Switch SpaHeaterGreen "Spa heater green" { channel="mqtt:topic:SpaControl:HeaterGreenChannel" }
Switch SpaHeaterRed "Spa heater red" { channel="mqtt:topic:SpaControl:HeaterRedChannel" }
Switch SpaHeater "Spa heater"
Switch SpaHeaterControl { channel="mqtt:topic:SpaControl:HeaterControlChannel" }
String SpaHeaterState "Spa heater state"

Number Spa_Display_Char1 "Spa display char 1" (g_SpaDisplayChars) { channel="mqtt:topic:SpaControl:DisplayChar1" }
Number Spa_Display_Char2 "Spa display char 2" (g_SpaDisplayChars) { channel="mqtt:topic:SpaControl:DisplayChar2" }
Number Spa_Display_Char3 "Spa display char 3" (g_SpaDisplayChars) { channel="mqtt:topic:SpaControl:DisplayChar3" }

String Spa_Display_Message "Spa display"
```
.rules
```
rule "SPA heater state"
when
    Item SpaHeaterGreen received update  or
    Item SpaHeaterRed received update 
then
    if(SpaHeaterGreen.state == ON || SpaHeaterRed.state == ON)
    {   
        SpaHeater.postUpdate(ON);
        if(SpaHeaterRed.state == ON){
            SpaHeaterState.postUpdate('HEATING')
        } 
        if(SpaHeaterGreen.state == ON){
            SpaHeaterState.postUpdate('NOT HEATING')            
        }
    } else {
        SpaHeater.postUpdate(OFF);
        SpaHeaterState.postUpdate('OFF')
    }    
end

rule "SPA set heater state"
when 
    Item SpaHeater received command
then
    if(SpaHeaterControl.state != SpaHeater.state)
    { 
        SpaHeaterControl.sendCommand(SpaHeater.state.toString)
    }
end

rule "SPA get display message"
when 
    Member of g_SpaDisplayChars changed
then
    var String result = ""
    
    result += Character.toString((Spa_Display_Char1.state as DecimalType).intValue);
    result += Character.toString((Spa_Display_Char2.state as DecimalType).intValue);
    result += Character.toString((Spa_Display_Char3.state as DecimalType).intValue);
    
    Spa_Display_Message.postUpdate(result.toString);
end
```

.sitemap
```
Frame label="Spa"{
        Text item=SpaCurrentTemperature icon="temperature"
        Setpoint item=SpaTargetTemperature icon="temperature" minValue=30 maxValue=40 step=1
        Text item=SpaHeaterState label="Heater [%s]" icon="heating"
        //Switch item=SpaPower
        Switch item=SpaPump
        Switch item=SpaHeater
        Switch item=SpaBubbles
        Text item=SpaCurrentTemperature_LastUpdate label="Last update"

        Text item=Spa_Display_Message label="Message on the display [%s]"
        //Switch item=SpaHeaterGreen
        //Switch item=SpaHeaterRed
    }
```

**Comment by torei** [comment]
here is my "thing" for openhab3
replace "layzspa/" with your MQTT base topic and ofc edit the broker ID (bridgeUID)

```yaml
UID: mqtt:topic:e0e61b7d3f:9471f681a9
label: Poolhaus / Lay-Z-Spa Miami
thingTypeUID: mqtt:topic
configuration:
  payloadNotAvailable: Dead
  availabilityTopic: layzspa/Status
  payloadAvailable: Alive
bridgeUID: mqtt:broker:e0e61b7d3f
location: Poolhaus
channels:
  - id: LockedState
    channelTypeUID: mqtt:number
    label: LockedState
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.LCK
  - id: PowerState
    channelTypeUID: mqtt:number
    label: PowerState
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.PWR
  - id: UnitState
    channelTypeUID: mqtt:number
    label: UnitState
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.UNT
  - id: BubbleState
    channelTypeUID: mqtt:number
    label: BubbleState
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.AIR
  - id: HeatGreenState
    channelTypeUID: mqtt:number
    label: HeatGreenState
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.GRN
  - id: HeatRedState
    channelTypeUID: mqtt:number
    label: HeatRedState
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.RED
  - id: PumpState
    channelTypeUID: mqtt:number
    label: PumpState
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.FLT
  - id: TargetTemperature
    channelTypeUID: mqtt:number
    label: TargetTemperature
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.TGT
      unit: °C
  - id: Temperature
    channelTypeUID: mqtt:number
    label: Temperature
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.TMP
      unit: °C
  - id: Display
    channelTypeUID: mqtt:string
    label: Display
    description: null
    configuration:
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.concat($.CH1,$.CH2,$.CH3)
  - id: SetTargetTemperature
    channelTypeUID: mqtt:number
    label: SetTargetTemperature
    description: null
    configuration:
      unit: °C
      min: 20
      formatBeforePublish: '{"CMD":0,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      max: 40
      commandTopic: layzspa/command
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.TGT
  - id: SetUnit
    channelTypeUID: mqtt:switch
    label: SetUnit
    description: null
    configuration:
      commandTopic: layzspa/command
      formatBeforePublish: '{"CMD":1,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      off: "0"
      on: "1"
  - id: SetBubbles
    channelTypeUID: mqtt:switch
    label: SetBubbles
    description: null
    configuration:
      commandTopic: layzspa/command
      formatBeforePublish: '{"CMD":2,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.AIR
      off: "0"
      on: "1"
  - id: SetHeater
    channelTypeUID: mqtt:switch
    label: SetHeater
    description: null
    configuration:
      commandTopic: layzspa/command
      formatBeforePublish: '{"CMD":3,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      off: "0"
      on: "1"
  - id: SetPump
    channelTypeUID: mqtt:switch
    label: SetPump
    description: null
    configuration:
      commandTopic: layzspa/command
      formatBeforePublish: '{"CMD":4,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      stateTopic: layzspa/message
      transformationPattern: JSONPATH:$.FLT
      off: "0"
      on: "1"
  - id: ResetQueue
    channelTypeUID: mqtt:switch
    label: ResetQueue
    description: null
    configuration:
      commandTopic: layzspa/command
      formatBeforePublish: '{"CMD":5,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      off: "0"
      on: "1"
  - id: RebootESP
    channelTypeUID: mqtt:switch
    label: RebootESP
    description: null
    configuration:
      commandTopic: layzspa/command
      formatBeforePublish: '{"CMD":6,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      off: "0"
      on: "1"
  - id: ResetTimes
    channelTypeUID: mqtt:switch
    label: ResetTimes
    description: null
    configuration:
      commandTopic: layzspa/command
      formatBeforePublish: '{"CMD":8,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      off: "0"
      on: "1"
  - id: ResetTimerChlorine
    channelTypeUID: mqtt:switch
    label: ResetTimerChlorine
    description: null
    configuration:
      commandTopic: layzspa/command
      formatBeforePublish: '{"CMD":9,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      off: "0"
      on: "1"
  - id: ResetTimerFilter
    channelTypeUID: mqtt:switch
    label: ResetTimerFilter
    description: null
    configuration:
      commandTopic: layzspa/command
      formatBeforePublish: '{"CMD":10,"VALUE":%s,"XTIME":0,"INTERVAL":0}'
      off: "0"
      on: "1"
```
