### DISCUSSION TITLE
Couple noob questions

### DISCUSSION THREAD

**Discussion by jarisiv** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#188] [General]
Hi and again thanks for the great project. I eventually found some time to solder all the parts together and managed to install the software as well. Couple noob questions:

1. What are the main differences between the master and dev branches? Is dev stable and ok to use or should I stick with master? I have now installed dev.
2. In the pump unit some buttons make the sound but not all even I have untick the audio from the Spa Config page. Is this how it should work?

Edit: I have a 2021 Helsinki with square pump model S100101.

**Comment by visualapproach** [comment]
Hi @jarisiv 

1. The latest and greatest goes into dev branch first. And also potential bugs that may have been introduced. If no big errors are reported I pull it into master branch when I feel it's a good time to do so. Usually with a new release/version tag. Occasionally the dev branch is unstable but I try to put a notice in readme in those cases.
2. Well, lets say it was the intention until you brought it up 😄 . I just updated the dev-branch with more silence.

Thank you for your post / Thomas

**Comment by jarisiv** [comment]
1. That's clear now!
2. Updated and now "Audio off" is truly audio off. Perfect! When audio on, following buttons give some sound feedback: Key Lock, Heater, Bubbles, Temp Down, On/Off. But following buttons don't give sound feedback: Timer, Unit Change, Pump/Filter, Temp Up. That really isn't a big issue if that's how it should be but for noobie like me I was first thinking that maybe I have done some mistake like bad soldering. Therefore I went back to soldering table and re-checked everything without any change in this behavior.

Then a new question.

3. Should the boot-up show the IP address of the device on the screen? My IP is 192.168.1.108 but during the boot-up I get following numbers in sequence: 92 -> 1 -> 1 -> 68 -> 1 -> 1 -> 10.

**Reply by visualapproach** [reply]
It shouldn't discriminate those buttons unless you actively made them disabled. Start up is (should) play a melody, show 'hello' and the IP address. Provided the sound is checked.
Do the silent buttons work at all? And can you for instance raise the target temp from the web gui?

**Reply by jarisiv** [reply]
Web gui works perfectly and all buttons in the unit also works despite the sound setting. I mean that when sound on only part of the buttons that I mentioned are giving the sound feedback in the unit.

In the boot-up I hear the melody (if sounds on), see the HELLO and then see this very weird number combo (92 -> 1 -> 1 -> 68 -> 1 -> 1 -> 10).

**Reply by visualapproach** [reply]
Weird

**Reply by jarisiv** [reply]
Yep but not a real issue as buttons still works. Btw, talking about buttons, any hint how to utilize e.g. C/F button to something else like controlling light switch in Home Assistant?

**Reply by visualapproach** [reply]
You just need to listen for mqtt topic BW2_0_0/button where the button's pretty name will be the payload. I can't show an example right now because my network is down.
You should also disable the button in globals.h. Instructions in the file

**Reply by jarisiv** [reply]
When you are back online would you mind to share an example? Thnks!

**Reply by visualapproach** [reply]
> 3. Should the boot-up show the IP address of the device on the screen? My IP is 192.168.1.108 but during the boot-up I get following numbers in sequence: 92 -> 1 -> 1 -> 68 -> 1 -> 1 -> 10.

Smashed this bug now. (dev branch for now)

**Comment by visualapproach** [comment]
Make a sensor for the buttons. See [here](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/blob/development/Code/Home%20assistant%20config/sensors.yaml)
Then make an automation that triggers on the button state, like below. It will toggle my awnings out/in when I press the TIMER button on the pump. Pretty neat if I may say so.
```
- id: '1629627523677'
  alias: Markiser ut/in från SPA-knapp
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.spa_button
    to: TIMER
    for: 00:00:05
  condition:
  - condition: state
    entity_id: group.familj
    state: home
  action:
  - service: cover.toggle
    target:
      entity_id: cover.markis_gra_2
  mode: single
```
The possible button states are:
	"NOBTN",
	"LOCK",
	"TIMER",
	"BUBBLES",
	"UNIT",
	"HEAT",
	"PUMP",
	"DOWN",
	"UP",
	"POWER",
	"HYDROJETS"

**Reply by visualapproach** [reply]
And to avoid upsetting the timer function in the pump, I have that button disabled in BWC_8266_globals.h:
```
//set to zero to disable display buttons. Order as above.
//Example: to disable UNIT and TIMER set 1,1,0,1,0,1,1,1,1,1,1
const uint8_t EnabledButtons[] = {1,1,0,1,0,1,1,1,1,1,1};
```

**Reply by visualapproach** [reply]
Never thought of it until now, but I think that disabling the NOBTN would be no good...

**Reply by jarisiv** [reply]
Thank you so much! Now having my "Please bring more beer to dad" TTS announcement button in the pump (Unit button).

**Reply by visualapproach** [reply]
Most useful button ever!

**Comment by jarisiv** [comment]
Couple more things. Any idea why all my HA entities becomes unavailable very often:

![image](https://user-images.githubusercontent.com/68715691/150523652-5b09863f-4aa8-4c4b-8809-7314e4822218.png)

I don't believe in bad WiFi coverage as having multiple Shelly devices in the jacuzzi area without any connection issues. Is there way to check the WiFi connection quality?

Then is it possible to reset chlorine add and filter change from HA?

**Reply by visualapproach** [reply]
Try adding expire_after: 700 in the binary-sensor status and see if that works.
It should be possible to reset the timers from mqtt. I'll add an example tonight

**Reply by visualapproach** [reply]
Actually I'm not sure the 700 will help. I need to look at it also later. Don't think the status msg is repeated but I'm AFH now.

**Comment by visualapproach** [comment]
Checkout the buttons.yaml file, and add it to your config. Add the button in lovelace. Test if it works.

**Reply by jarisiv** [reply]
Cl reset did work but filter reset not.

**Reply by jarisiv** [reply]
Seems that filter reset did reset total energy consumption.

**Reply by visualapproach** [reply]
Oops, sorry. Corrected now. I had a parallax error and wrote down the wrong commands. Updated now.

**Reply by jarisiv** [reply]
Thanks, now working!

**Comment by visualapproach** [comment]
Is it only the status sensor that's unavailable, or is it all the spa entities, or other entities as well?

**Reply by jarisiv** [reply]
It is all entities that goes unavailable. Sometimes it can be only couple seconds but sometimes also multiple minutes. I have noticed that during those unavailable times also the web configuration cannot be accessed. So based on that I don't think that is MQTT or HA issue. Could it really relate to the WiFi link quality? Can that be monitored someway?

**Reply by visualapproach** [reply]
Not my expertise but I guess it's a possibility. If you check BW_2.0.0/MQTT_Connect_Count topic it shows how many times mqtt has reconnected. Might be a hint.

**Reply by jarisiv** [reply]
Yeah almost 100 times during 3 day period.

**Comment by chunkysteveo** [comment]
Sounds like a wifi issue... I have a wifi mesh and it's never dropped a packet. 100 disconnects would suggest a hardware/connection issue.

**Reply by jarisiv** [reply]
I will try to test this by taking the UniFi AP closer to the pool area.

**Comment by jarisiv** [comment]
Thinking is it possible to somehow get the Exx (e.g. E02) errors in to the HA? That would be awesome. I found one example here by using the Node-RED but I am not using that.

**Reply by visualapproach** [reply]
updated code and new yaml (not tested)

**Reply by jarisiv** [reply]
Is that also working with 6-wire version?

**Reply by visualapproach** [reply]
No but you just have to make sensor for char1-3 in the same manner. If char1=='E' you're in trouble

**Reply by jarisiv** [reply]
Got it and those values that CH1-3 are giving are in hex?

**Reply by visualapproach** [reply]
They are ASCII codes in decimal

**Reply by jarisiv** [reply]
Thanks! So monitoring for possible 69 (E).

**Reply by jarisiv** [reply]
Actually it seems to be 101 (e).

**Reply by jarisiv** [reply]
Now having an automation that will make a TTS announcement in the speakers and also push notification on Android device (Jacuzzi Pump Malfunction). Very very handy feature. Tested and works!

**Reply by chunkysteveo** [reply]
Aaaaand... the Yaml to help me do the same would look like....?! 🤏🏻🙏

**Reply by jarisiv** [reply]
First in configuration.yaml I made a sensor for display ch1 (as well as ch2 and ch3) and a binary sensor for pump malfunction:

```
sensor:
  - platform: mqtt
    name: "Jacuzzi Display CH1"
    state_topic: "layzspa/message"
    value_template: "{{ value_json.CH1 }}"
    availability_topic: "layzspa/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"

binary_sensor:
  - platform: template
    sensors:
      jacuzzi_pump_malfunction:
        friendly_name: "Jacuzzi Pump Malfunction"
        value_template: >
          {% if is_state('sensor.jacuzzi_display_ch1', '101') %}
            Yes
          {% else %}
            No
          {% endif %}
```

And then the automation itself in automations.yaml:

```
- id: '1643553671042'
  alias: Jacuzzi Pump Malfunction
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.jacuzzi_pump_malfunction
    to: 'on'
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_google
      language: fi
      message: Hälytys! Porealtaan pumppu vikatilassa!
  - service: notify.mobile_app_kb2003
    data:
      title: Alarm
      message: Jacuzzi Pump Malfunction
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  mode: single
```
