### DISCUSSION TITLE
Home Assistant temperature recording readings

### DISCUSSION THREAD

**Discussion by Bishbosh02** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#258] [Q&A] [answered]
I have some odd temperature recordings, they go very low has anyone seen this before I am using the development branch but this also happened on an old version so don't think its a new issue see pic
![Temp](https://user-images.githubusercontent.com/9953147/166646957-64a84b30-a4d6-488f-a1da-5e7ec2198d4a.JPG)

**Comment by visualapproach** [comment]
How does the graph on airbubbles/pump look like? Can it be a noisy data transmission that flips the unit bit occasionally? In that case it should also be visible on the other states I guess.

**Reply by Bishbosh02** [reply]
The spa target also has the issue and this just comes from the control board? but is also affecting air bubbles so looks like a noise issue

**Reply by visualapproach** [reply]
Yeah probably. I don't remember your setup now but possible mitigations are shorter wires and low pass filters

**Comment by Skeletorjus** [comment]
https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/issues/236

I have the same ting. It's honestly not a big deal, and I've made some template sensors in Home Assistant that filters out the rogue values. I did build a board with shorter wires as suggested, but must have messed up in another way since I couldn't get it working at all, so that is still on ny todo-list.

**Reply by Bishbosh02** [reply]
Can you share your template sensors 👍

**Reply by Skeletorjus** [reply]
Sure!
For temperature sensors I use two templates. One filters out all values outside scope. I use celsius, so everything between 5 and 41 is discarded. Then I have another trigger based template sensor that filters out all values from the first one that are present for less than 5 seconds and/or unavailable  to remove the "blips".
The original temperature as reported by the ESP has been renamed to `sensor.layzspa_temperature_raw` in Home Assistant.

<details>
  <summary>Temperature sensor</summary>

```
template:
  - sensor:
      - name: Layzspa Temperature filtered
        unique_id: sensor.layzspa_temperature_filtered
        state: "{{ states('sensor.layzspa_temperature_raw') | int }}"
        unit_of_measurement: "°C"
        availability: "{{ ((states('sensor.layzspa_temperature_raw') | int) > 5) and  ((states('sensor.layzspa_temperature_raw') | int) < 41) }}"
        device_class: temperature

  - trigger:
      - platform: state
        entity_id: sensor.layzspa_temperature_filtered
        for: "00:00:05"
    sensor:
      - name: Layzspa Temperature
        unique_id: sensor.layzspa_temperature_sanitized
        state: "{{ states('sensor.layzspa_temperature_filtered') | int }}"
        unit_of_measurement: "°C"
        availability: >-
          {{ not is_state('sensor.layzspa_temperature_filtered','0') and not is_state('sensor.layzspa_temperature_filtered','unavailable') and not is_state('sensor.layzspa_temperature_filtered','unknown') }}
        device_class: temperature
```
</details>

I use template binary sensors to clean up states of switches and binary sensors. These turn on only after the parent switch/sensor has been on for 5 seconds, and will remove all the blips.
Example:

<details>
  <summary>Binary state sensor</summary>

```
template:
  - binary_sensor:
      - name: Layzspa Pump
        unique_id: binary_sensor.layzspa_pump
        state: >-
          {{ states('switch.layzspa_pump') }}
        delay_on:
          seconds: 5
```
</details>

In UI I use [button-card](https://github.com/custom-cards/button-card) and configure it to show the state from the template binary sensor, and to toggle `switch.layzspa_pump` when clicked.
<details>
  <summary>Card</summary>

```
type: custom:button-card
color: auto
color_type: card
entity: binary_sensor.layzspa_pump
icon: mdi:pump
hold_action:
  action: more-info
tap_action:
  action: call-service
  service: switch.toggle
  service_data:
    entity_id: switch.layzspa_pump
name: Pump
styles:
  card:
    - height: 80px
```
</details>

The only thing in the UI that still is irregular is the history of the climate control. I'm sure this can be worked around by creating a secondary MQTT climate control and move values between that and the original climate control by way of automations, but I don't really think it's needed.

I guess this could be done in the ESP itself with configurable debouncing before reporting to MQTT and/or a min/max for temperature readings, but as @visualapproach stated in https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/issues/236#issuecomment-1078011466, this would only be a workaround for the root hardware issue.
