### DISCUSSION TITLE
Set Ambient Temp via HA

### DISCUSSION THREAD

**Discussion by jamesonuk** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#450] [Q&A] [answered]
So I have everything setup via MQTT and that is all working fine but the Web UI doesn't play nicely and doesn't actually update.

The ambient temperature has been added to HA as a sensor but there doesn't appear to be a way to set it?

I tried publishing 
```
{
  "CONTENT": "STATES",
  "TIME": 1676288732,
   "AMB": 10 
}
```
to `layzspa/message` topic without joy.

I am looking to automate is via the value I get from the accuweather integration but I can't figure out how to set it....

**Comment by visualapproach** [comment, marked as answer]
I'll show you after work. But it's  to the command topic you wanna send to. Call you back

**Reply by jamesonuk** [reply]
That was enough to point me in the right direction and do some searching....
topic was `layzspa/command`
payload was `{"CMD":15,"VALUE":10,"XTIME":0,"INTERVAL":0}`
15 is `setAmbient` (amongst others in `websocket.js`)

Not 100% sure of XTIME and INTERVAL but I guess that isn't needed for this and is to do with scheduling

**Reply by visualapproach** [reply]
Yes, this is my automation (change the sensor to whatever sensor you use):

```
alias: Lay-z-spa uppdatera utetemperaturen
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.outside_temperature
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.outside_temperature
        state: unknown
      - condition: state
        entity_id: sensor.outside_temperature
        state: unavailable
action:
  - service: mqtt.publish
    data:
      topic: layzspa/command
      payload_template: >-
        {"CMD":15,"VALUE":{{ states("sensor.outside_temperature")|round
        }},"XTIME":0,"INTERVAL":0}
mode: single
```
