### DISCUSSION TITLE
Home Assistant set Ambiente Temperature

### DISCUSSION THREAD

**Discussion by goofy79** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#495] [General]
Hello, 

i try to set the Temperature from a Sensor to the Ambiente Temperatur on LayZSpa

in the automations.yaml i write :
```
alias: sendtemp
trigger:
- platform: state
  entity_id: sensor.heizung_aussentemperatur
action:
- service: mqtt.publish
  data:
    topic: layzspa/message
    payload: "{{ trigger.to_state.state }}"
```

I think the Payload is wrong - can you help me ?
