### DISCUSSION TITLE
MQTT in Home Assistant

### DISCUSSION THREAD

**Discussion by sjeffrey101** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#52] [Show and tell]
Ok ive managed to get the MQTT of V2 working in home assistant and though i'd share.

![image](https://user-images.githubusercontent.com/67539382/103467618-cc917180-4d48-11eb-9191-60e6e0ac8db0.png)

In configuration.

```
climate:
  - platform: mqtt
    name: SPA Temperature
    max_temp: 40
    min_temp: 20
    precision: 1.0
    temperature_unit: "C"
    modes:
      - "off"
      - "heat"
    mode_state_topic: "BW_2.0.0/message"
    mode_state_template: >-
      {% if value_json.RED == 1 %}
        heat
      {% elif value_json.GRN == 1 %}
        heat
      {% else %}
        off
      {% endif %}  
    action_topic: "BW_2.0.0/message"
    action_template: >-
      {% if value_json.RED == 1 %}
        heating
      {% elif value_json.GRN == 1 %}
        idle
      {% else %}
        off
      {% endif %}          
    temperature_state_topic: "BW_2.0.0/message"
    temperature_state_template: "{{ value_json.TGT }}"
    current_temperature_topic: "BW_2.0.0/message"
    current_temperature_template: "{{ value_json.TMP }}"
    temperature_command_topic : "BW_2.0.0/thermostatcommand"
    power_command_topic: "BW_2.0.0/command"
    payload_on: '{"CMD":3,"VALUE":1,"XTIME":0,"INTERVAL":0}'
    payload_off: '{"CMD":3,"VALUE":0,"XTIME":0,"INTERVAL":0}'
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"

sensor:
  - platform: mqtt
    name: "SPA Temperature"
    state_topic: "BW_2.0.0/message"
    value_template: "{{ value_json.TMP }}"
    unit_of_measurement: '°C'
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
  - platform: mqtt
    name: "SPA Target Temperature"
    state_topic: "BW_2.0.0/message"
    value_template: "{{ value_json.TGT }}"    
    unit_of_measurement: '°C'
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"

switch:
  - platform: mqtt
    name: "SPA Pump"
    state_topic: "BW_2.0.0/message"
    command_topic: "BW_2.0.0/command"
    value_template: "{{ value_json.FLT }}"
    payload_on: '{"CMD":4,"VALUE":1,"XTIME":0,"INTERVAL":0}'
    payload_off: '{"CMD":4,"VALUE":0,"XTIME":0,"INTERVAL":0}'
    state_on: 1
    state_off: 0
  - platform: mqtt
    name: "SPA Heat"
    state_topic: "BW_2.0.0/message"
    command_topic: "BW_2.0.0/command"
    value_template: >-
      {% if value_json.RED == 1 %}
        1
      {% elif value_json.GRN == 1 %}
        1
      {% else %}
        0
      {% endif %}  
    payload_on: '{"CMD":3,"VALUE":1,"XTIME":0,"INTERVAL":0}'
    payload_off: '{"CMD":3,"VALUE":0,"XTIME":0,"INTERVAL":0}'
    state_on: 1
    state_off: 0
  - platform: mqtt
    name: "SPA Bubbles"
    state_topic: "BW_2.0.0/message"
    command_topic: "BW_2.0.0/command"
    value_template: "{{ value_json.AIR }}"
    payload_on: '{"CMD":2,"VALUE":1,"XTIME":0,"INTERVAL":0}'
    payload_off: '{"CMD":2,"VALUE":0,"XTIME":0,"INTERVAL":0}'
    state_on: 1
    state_off: 0
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"

binary_sensor:
  - platform: mqtt
    name: "SPA Heating"
    state_topic: "BW_2.0.0/message"
    value_template: "{{ value_json.RED }}"
    payload_on: 1
    payload_off: 0
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
```

then thermostat/climate component works apart from setting the temperature, to do this i needed an extra automation to send the full command to the spa

in automations

```
- id: '1609539044283'
  alias: SPA MQTT Relay
  description: ''
  trigger:
  - platform: mqtt
    topic: BW_2.0.0/thermostatcommand
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      payload: '{"CMD":0,"VALUE":{{trigger.payload}},"XTIME":0,"INTERVAL":0}'
      topic: BW_2.0.0/command
  mode: single
```

This seems to be working well for me, so thought i'd share.  If anyone has any suggestions i'd e interested to hear also.

@visualapproach thanks so much for this great project.

thanks

stuart

Edit:  updated the headings which i had wrong/
Edit:  added availability mqtt topics.

**Comment by bertieuk** [comment]
Huge thanks for this!! New to Home Assistant + MQTT so this was a massive help!

Had to make some changes for it to work/validate -

sensors: > sensor:
switches: > switch:
binary_sensors: > binary_sensor:

**Reply by sjeffrey101** [reply]
@bertieuk oops, sorry i have my stuff in seperate files and obviously didnt double check the headings.  Ive corrected the above post.

hopefully thats working well for you, if you make any other improvements or have ideas let me know.  I'm also quite new to HA and MQTT, so i managed to coble this together with google and the FAQ in this github.

**Comment by sjeffrey101** [comment]
just added availability topics, to make it unavailable when offline.

**Comment by bertieuk** [comment]
Thought I'd add my two automations created to turn off / on the heater. As most know, the temperature tolerance of the spa heater is +/- 2 degrees, so will continue to heat beyond the target temp or not heat until colder than target temp.

So I created two automations to turn the heater off as soon as goes above my target temp and turn on when goes below. p.s This is a hard coded temp, I tried to compare against sensor.spa_target_temperature but couldn't get this to work (will post this code in reply for anyone else to try and fix)

```
- id: '1610457303259'
  alias: Turn off Spa Heat if 39
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.spa_temperature
    above: '38'
  condition:
  - condition: state
    entity_id: binary_sensor.spa_heating
    state: 'on'
  - condition: and
    conditions:
    - condition: time
      after: 07:30:00
      before: '19:00:00'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.spa_heat
  mode: single
- id: '1610966637504'
  alias: Turn on Spa Heat if 37
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.spa_temperature
    below: '38'
  condition:
  - condition: time
    before: '16:00'
    after: 09:00
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.spa_heat
      state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.spa_heat
  mode: single
````

**Reply by bertieuk** [reply]
Version to compare against target temp but doesn't work for me:

```
- id: '1610457303259'
  alias: Turn off Spa Heat if Greater than Target
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(sensor.spa_temperature)|float > states(sensor.spa_target_temperature)|float }}'
  condition:
  - condition: state
    entity_id: binary_sensor.spa_heating
    state: 'on'
  - condition: and
    conditions:
    - condition: time
      after: 07:30:00
      before: '19:00:00'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.spa_heat
  mode: single
- id: '1610966637504'
  alias: Turn on Spa Heat if Less than Target
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(sensor.spa_temperature)|float < states(sensor.spa_target_temperature)|float }}'
  condition:
  - condition: time
    before: '16:00'
    after: 09:00
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.spa_heat
      state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.spa_heat
  mode: single
```

**Reply by bertieuk** [reply]
Finally, this is my app / Apple Watch complication to show the spa temp - it's basic and I'm sure there are better methods (show if heating, etc.) but works for now.
![IMG_5611](https://user-images.githubusercontent.com/13354213/106383260-dbf1f200-63bc-11eb-9f13-542f5bbb23e3.PNG)
![IMG_5612](https://user-images.githubusercontent.com/13354213/106383264-dd231f00-63bc-11eb-9f11-f0f661627a4a.PNG)

**Reply by jlockham** [reply]
That looks great! - Are you able to share how you built the watch complication in Swift (or the code)?

**Reply by bertieuk** [reply]
> That looks great! - Are you able to share how you built the watch complication in Swift (or the code)?

It's built in the iOS Home Assistant app (first screenshot) and then appears as a watch complication.

**Reply by ncrutch13** [reply]
I just completed setting up this to work with my SPA. I tried out the code you had above, but I ran into problems with the numeric state triggers not firing reliably in Home Assistant. To work around it, I wrote another Automation in HA. It basically runs every minute and controls the temperature that way. It's a bit brute force, but it's such a small amount of work for the server I am not worried about. Posting it here in case it can be of help to anybody else. 

Also I have some code in there to ignore the call for heat during the expensive power time for my area, you can of course delete that if not relevant for you. 

```
- id: '1641099140874'
  alias: Control Spa Heat
  description: Set to 103
  trigger:
  - platform: time_pattern
    minutes: /1
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.spa_temperature
        above: '103'
      - condition: and
        conditions:
        - condition: state
          entity_id: switch.spa_heat
          state: 'on'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.spa_heat
    - conditions:
      - condition: numeric_state
        entity_id: sensor.spa_temperature
        below: '103'
      - condition: and
        conditions:
        - condition: state
          entity_id: switch.spa_heat
          state: 'off'
        - condition: not
          conditions:
          - condition: time
            after: '15:00:00'
            before: '20:00:00'
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.spa_heat
    default: []
  mode: single
```

**Comment by sjeffrey101** [comment]
nice work.....  i wonder why using the target temp doesnt work.  I may use this automation as the 2 degree issue is rather annoying.

**Reply by cyberfly79** [reply]
so possibly (i can't try yet)

- id: 'turn_off_spa_heat_if_greater_then_target'
  alias: Turn off Spa Heat if Greater than Target
  description: ''
  trigger:
    - platform: time_pattern
      minutes: "/1"
      seconds: 0
  condition:
  - condition: template
    value_template: '{{ states(sensor.spa_temperature)|float > states(sensor.spa_target_temperature)|float }}'

**Comment by visualapproach** [comment]
Great contributions guys! YAML isn't my first language so nice to see some examples.

**Comment by Polar-Development** [comment]
With HomeSeer I created quite a few logical events.  I noticed that my running costs reduced by almost 50% after so was well worth the effort.

I noticed that the temperature is clearly taken from a smaller sample, and because my logic switches off the pump and heater once set temperature is reached, the water having its temperature tested was a smaller sample that stood still and got colder quicker.  I there for have the heater (and pump) switch on if the temp goes below 5 degrees lower than the measured temp and switches off once it hits target temperature. This stopped the system form switching on and off every few minutes to instead every hour or so (sometimes 4 > 5 hours).  As soon as the pump starts the temp rises quickly to reflect the actual temp in the tub, this is often about 2 degrees below.

I have 3 temp set schedules, 32c @ 1am, 35c @ 9am, 40c @ mid day.  The result is each evening the tub it as required, its fine during the day if the kids want a splash, and its not costing money over night (and less so during the day also).  The all on / all off method works well because to keep temp correct the pump needs to be on for quite a while as heating is taking place, so no real need for extra time spent just using the pump by itself.

I am working to adjust my logic based on outside temp, as the colder it is, the faster the small sample of water that is tested for temp will cool, and the opposite in the summer when its warmer. So like with my house heating I shall likely adjust the off set over time dependant on the outside temp.  Of course this will take a few months to get ideal with testing etc.

I also have it set up with geo location on our home system so if we are away it wont heat, but will pump for 2 hours every 10 to ensure the tub is circulated offered some filtration.

I have other things set up to regarding garden lighting and notifications etc.

The set up works really well, hope my comments spark some imagination with others for use.

Thanks again for great work on this.

**Reply by sjeffrey101** [reply]
thats really interesting.  Are you UK based?  We are and its pretty cold out, so im just trying to experiment with how much heat is lost over night and how long it takes to warm back up.

My smart meter, is showing a MASSIVE increase in costs at the moment, so yes trying to become more economical is high on my list.  

Also the variation in temperature is huge.  we normally set at 38, and sometimes feels cold and other times hot, not often its just right.  2 degrees each way is a massive variation, so yes will look to handle the thermostat side myself.

is the pump expensive to run?  Would circulating this for 30 seconds every 10 minutes and taking the temp sample then use much electric.

im also toying with the idea of an electric tarrif that is cheaper over night, so i could do most the grunt work then....  however its a long time between then and the evening when i use the tub, so may actually not be worth it.

**Reply by visualapproach** [reply]
Is the pump expensive?

It's rated at 40 Watts so that part is cheap compared to the heater (~2000 W) but it will wear out eventually which should be considered money- and effort wise

**Reply by sjeffrey101** [reply]
good question, i currently leave mine on, and havent measured electric use of just the pump, but maybe its not worth the effort, to figure out switching on/off

**Reply by techno-Dev-81** [reply]
How did you get this working with HomeSeer?
I've been looking for a way to connect HS with the Lay-Z-Spa.
Have the Bestway app on my mobile, but not integrated into HS.
Only being on when home would be a bonus for cost savings.

**Comment by Polar-Development** [comment]
Hi, Yes UK based.  I agree with a few degrees making a big difference and also the costs for running it, hence my quest.  I like the idea of pump circulation to get better temp readings but any regular on/off of the pump I felt may shorten its life.  Also I am looking into Wi-Fi enabled PH & Chlorine testers - they often have temp too, so eventually I think I will take temp from the tub not the egg and so hopefully it will be more accurate.

I found keeping the cover well inflated and situating the tub out of windy areas worked well for maintaining / preserving temp.  I have considered a sort of insulating jacket to wrap round it also - but I think my thinking is going a step too far here :-)

**Reply by sjeffrey101** [reply]
i dont think my wife would be too happy with a tub jacket.  yes, actually our lid itsnt well fitting right now, it doesnt seem to be sitting inside properly.  I think this might be because my sides are feeling over inflated due to blowing up cold and then the air must have expanded.....  i need to deflate slightly.

yes i did wonder about the life.

Ive also wondered about an external temp monitor for more accuracy (esp when pump is off).

i had a quick look for chlorine monitors, couldnt find anything the looked cost effective?

Stu

**Reply by bertieuk** [reply]
I leave my pump on 24x7, change filters every 3 days. The temp reading becomes very erratic with the pump off. I use it every day so keeping it circulated works best for the water quality. I've only emptied it once since August last year, and that was to move it for some building work.

I have two layers of foil bubble wrap between the inflated tub and the outer cover - both the tub itself and the lid! Think it has helped as the temp doesn't drop as quick as it was in ~Sept/Oct. Bit of a struggle to get in with it all semi-deflated, but worth it in the end. https://www.amazon.co.uk/gp/product/B08CGRSKX6 

I'm also in UK, and have economy 7 rate overnight, so bump the temp up to 40 at 1am and heats overnight and find it has dropped to 37 by 3/4 in the afternoon.

**Reply by sjeffrey101** [reply]
ok im loosing way more heat then that.  I turned it off last night at 2230 after we got out.  Now at 12noon its down to 30.  No wonder my electric has shot up.  I need to get the lid seated a bit better, and order some tinfoil bubble wrap.

with my drop, there is no point utilising the economy 7 rates as i have to heat in the day to get back to temp any way.

**Reply by wyliecoyoteuk** [reply]
I have the Hawaii, It is sitting on PIR insulation board, and I replaced the balloon in the lid with the same, wrapped in polythene sheet, attached with waterproof double-sided tape. It now folds in the middle like a hard tub lid.  I have added foil bubble wrap around the outside. Temperature loss is about 3-4 degrees over 12 hours at the moment.  We use it in the morning and afternoon. Heat it from 6AM to 4 or 5PM. I have put it in a summerhouse now, but that doesn't seem to have made as much difference. 
I have a wifi pump and a spare non-wifi that I am planning to modify. The wifi pump has a +/-1 degree hysteresis.

**Reply by sjeffrey101** [reply]
would be interesting to see photos.....  the floor side is easy to achieve, not sure about the lid.  Also dont think my wife would be too happy with any additional height.

**Reply by wyliecoyoteuk** [reply]
No extra height, a lot neater and lighter. When I took the balloon out, it was half full of water.
https://user-images.githubusercontent.com/79256941/110313631-9f8a6500-7ffe-11eb-843e-6740ff877cc2.mp4

**Reply by sjeffrey101** [reply]
i mean the extra height if your put board under the tub?

**Reply by wyliecoyoteuk** [reply]
Oh, sorry. depends on how thick you want it. 30mm is good enough to make a real difference.
I have 50mm, and it is on a decking floor.

**Reply by cfarrar1** [reply]
> I have the Hawaii, It is sitting on PIR insulation board, and I replaced the balloon in the lid with the same, wrapped in polythene sheet, attached with waterproof double-sided tape. It now folds in the middle like a hard tub lid.  I have added foil bubble wrap around the outside. Temperature loss is about 3-4 degrees over 12 hours at the moment.  We use it in the morning and afternoon. Heat it from 6AM to 4 or 5PM. I have put it in a summerhouse now, but that doesn't seem to have made as much difference. 
> 
> I have a wifi pump and a spare non-wifi that I am planning to modify. The wifi pump has a +/-1 degree hysteresis.

I like the idea of PIR insulation lid! My lid balloon is full of water & has deformed so may give this idea a go.
It's worth putting foil wrap inside, I did this last year and has made such a difference. I loose around 5-7 degrees from 10pm to 1pm when the heater comes back on.
I have mine automated to heat only during economy 10 hours.

**Comment by Polar-Development** [comment]
I was not aware wattage between pump / heater but it does not come as a surprise that the expensive bit is the heater. Hence wanting to reduce its use as effectively as I can.

For the Jacket I was considering purchasing an old broken tub off the net, using that to be filled with some sort of loft insulation, then the bottom cut off and a join with clips on, the end result would (Hopefully) be an outside jacket that matches exiting external, and the clips would join where the pump is.  I will see if I do or do not pursue this.

I am still researching WIFI enable testers, only ones I have found are expensive.   temp sensors out can get cheap enough.

**Comment by Polar-Development** [comment]
If I had economy 7 I too would operate similarly to you.

The bubble wrap is a very interesting idea.  To confirm you add this on top of the inflated cover under the fabric cover (so between the top of the inflated li-lo type thing but under the cloth cover so basically you would not know its there.  Correct?

**Reply by bertieuk** [reply]
Yep, between the inflated cover and fabric cover. I used foil tape to join lengths together then drew round the inflated lid. You can't tell it's there, or around the tub. I even wrapped off-cuts round the egg > tub pipework. And I have it underneath too!

**Comment by Polar-Development** [comment]
"...or around the tub"  So you have done a jacket also!?

I am almost certainly going to do the same with the lid - this sounds like a very good idea and likely where most heat escapes.

Cant help but chuckle at the idea you have silver bubble wrap on everything (i know you have explained in reality you do not) and so it may look like your bathing in a silver space ship! :-)

**Reply by bertieuk** [reply]
Other than around the egg pipes, and a little stuck out from underneath, it's invisible. The 10m roll is long enough to go round the tub twice, underneath and inside the lid.
![Photo-2021-01-26-11-00-01_5595](https://user-images.githubusercontent.com/13354213/106457828-728ae580-6487-11eb-863c-cc2bd6bd8f1e.JPG)
![Photo-2021-01-26-11-08-59_5596](https://user-images.githubusercontent.com/13354213/106457835-7585d600-6487-11eb-9120-0c5fada29d6d.JPG)

**Reply by Polar-Development** [reply]
Looks great - cant see a thing.  I am certain to copy with the lid, I have the Helsinki however so now cover around the sides to be able to hide an additional lining, hence my comment prior for an alternate idea.

thank you for shearing.

**Comment by cfarrar1** [comment]
If you have HA cloud then you can integrate Alexa into HA aswell which will allow voice control, or in my case ask her what the temp is.
You'll also need the Alexa media player HACS repo (google how to install)

Then add the following to the scripts.yaml

```
spa_temperature:
  alias: Spa Temperature
  sequence:
  - service: notify.alexa_media_last_called
    data:
      data:
        type: tts
      message: '"The temperature is {{states(''sensor.spa_temperature'')|replace(''.'',
        '' point '') }} degrees"'
  mode: single

```
This will then create a scene in Alexa which you can create a routine to trigger the scene when you say "Alexa, what's the spa temperate" = she will read the temp out to you.
