### DISCUSSION TITLE
Ambient Temp from HA

### DISCUSSION THREAD

**Discussion by TheSimTek** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#587] [General]
Quick question on the interaction between HA and the Lay-Z-Spa Module.

How do I pass on the ambient temperature from Home Assistant to the module?  I am using both the Ecowitt entity from my own weather station and the inbuilt card Forecast Home.

thanks.

**Comment by visualapproach** [comment]
Make an automation like this. If using F use CMD:14. Or was it 16? Look in the manual.
```
alias: Lay-z-spa uppdatera utetemperaturen
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.temp_rh_ute_temperature
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.outside_temperature
        state: unknown
      - condition: state
        entity_id: sensor.outside_temperature
        state: unavailable
action:
  - service: mqtt.publish
    data:
      topic: layzspa/command
      payload_template: >-
        {"CMD":15,"VALUE":{{ states("sensor.temp_rh_ute_temperature")|round
        }},"XTIME":0,"INTERVAL":0}
mode: single
```
