### DISCUSSION TITLE
Error notifications - e.g. E02 error?

### DISCUSSION THREAD

**Discussion by c-soft** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#594] [Q&A] [answered]
I’m getting E02 error every now and then due to clogged filter, or other issues.

Would be great to get notification from Home Assistant (or otherwise) when this happens.

I’ve looked through all the states available but couldn’t find any indication. 

Is it possible somehow?

**Comment by Skeletorjus** [comment, marked as answer]
There are multiple ways to do this, but one method is to create a sensor that mirrors whatever is on the display and make an automation that sends a notification if the sensor is E02.
```

mqtt:
  sensor:
    - name: "Layzspa Display"
      unique_id: "sensor.layzspa_display"
      state_topic: "layzspa/message"
      icon: mdi:fit-to-screen
      value_template: >-
        {% set ASCII = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx !x#$%&'()*+`-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz" %}
        {% set ch1=ASCII[value_json.CH1] %}
        {% set ch2=ASCII[value_json.CH2] %}
        {% set ch3=ASCII[value_json.CH3] %}
        {{ch1}}{{ch2}}{{ch3}}
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"
```

**Reply by c-soft** [reply]
Thanks, i will try that!
Out of curiosity, what ore other ways?
Or maybe is there a documented Mqtt topic list with info?

**Reply by visualapproach** [reply]
One other way is to wait for the next beta update ;-)

**Reply by visualapproach** [reply]
Now you can catch the "ERR" field for values other than 0. Sensor is autodiscovered in HA

**Reply by chumleychuff** [reply]
This is great news - I have upgraded to the beta and can now see the error field but I can't setup automation based on it, for some reason it's not showing in the list of selectable entities in HA - do you know why that might be?

**Reply by visualapproach** [reply]
need a restart? Check the entity name under entities, and check in developer/states for "error". It should show there

**Reply by Skeletorjus** [reply]
@chumleychuff 
Try this (name of sensor may vary):
```
trigger:
  - platform: state
    entity_id:
      - sensor.layzspa_error
    to: "2"
```

**Reply by chumleychuff** [reply]
Thanks Skeletorjus - this is what worked for me:

```
alias: Skeletorjus Trigger
description: "Skeletorjus Trigger"
trigger:
  - platform: state
    entity_id: sensor.layzspa_wifi_controller_layzspa_error
    to: "2"
condition: []
action:
  - service: notify.persistent_notification
    data:
      message: LayZSpa - Error Code has changed - Skeletorjus
      title: LayZSpa - Error Code has changed - Skeletorjus
  - service: notify.mobile_app_myphone
    data:
      message: LayZSpa - Error Code has changed - Skeletorjus
mode: single
```
