### DISCUSSION TITLE
Homeassistant set target temp?

### DISCUSSION THREAD

**Discussion by joukoy** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#727] [Q&A] [answered]
I can see the target temperature sensor in HA, but is it possible to change target temp in automation?
So I can raise the target temperature when electricity is cheap, drop a couple of degrees when it's expensive, not just stop/start heating.

**Comment by visualapproach** [comment, marked as answer]
Yes, use the service 'climate: set target temperature' in your automations

**Comment by Peele69** [comment]
Hi,
I hope I can use this thread.
I am trying to do an automation where I want to heat the pool when the solar panels give much power. I have the solar inverter integrated to HA but can't get this to work. Is it possible to do with an automation or is it more complicated? For example, if solar panels give over 2kw the heater should start, and when panels give under 2kw heater goes off. I am very new to HA...

**Reply by visualapproach** [reply]
Hi @Peele69 ! It should be doable indeed. Make a new automation and make it trigger when 'solar power' is above x kW. Action: turn on switch 'layzspa_heat'
Above is from my head only, if you need more specific info you can post a picture/text of your automation and we go from there

**Reply by visualapproach** [reply]
Like this to turn the heater ON:
```
description: "Turn on layzspa heat when solar power is high"
mode: single
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.solar_power
    for:
      hours: 0
      minutes: 2
      seconds: 0
    above: 2000
condition: []
action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.layzspa_heat_regulation
```
The "for 2 minutes" is to avoid rapid changes when the solar output is producing just around the 2000 W limit.
Make another automation that turns the heater off when BELOW 2000 W for 2 minutes. Or 1900 W to have some hysteresis.
