### DISCUSSION TITLE
Time to ready imported into Home Assistant?

### DISCUSSION THREAD

**Discussion by chunkysteveo** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#835] [Q&A] [answered]
As per the title - does the T2R - Time to Ready get imported into Home Assistant? I can't see the sensor in my entity list?

**Comment by chunkysteveo** [comment, marked as answer]
OK - I'm seeing my code base has the "Time to ready" and "Ready state" overriding each other, and I can see the develop branch has this extracted out.

I've created my own MQTT sensor to extract the T2R time in hours.

Anyone interested in a handy timestamp template for Home Assistant... Create a Helper > Template, and stick this in it!

```
{{ (
(now() + timedelta(weeks=52)) | as_datetime | as_local
if
            states('sensor.layzspa_layzspa_time_to_ready_time')
            | float < 0 
            else
            (now() + timedelta(hours=states('sensor.layzspa_layzspa_time_to_ready_time') | float)) | as_datetime | as_local)     
}}
```

Replace the sensor for the correct time_to_ready sensor that shows the hours remaining.

If you add it as a small badge or similar, HA will auto translate the time remaining, so you get something useful, 
![image](https://github.com/user-attachments/assets/c28965f7-a42c-441d-be77-5679a3b3a2cd)
or if it's off, something not ridiculous - like this:
![image](https://github.com/user-attachments/assets/92838eeb-06f1-438e-ba8f-377e9e2a803a)

**Comment by dempanator** [comment]
Slightly off topic but related... I cannot seem to get my MQTT connected to the module. I have local connection & control but the MQTT Connect fails. I've checked what I thought was the credentials but now I'm not sure. In the Broker config it shows homeassistant as a user name and then the password if not visible. Anything you could suggest to help would be very helpful!

**Reply by chunkysteveo** [reply]
Sounds like you don't have the right MQTT details inputted. Download MQTT Explorer and try connecting to your HA MQTT installation. If you manage to connect, that should be the credentials and details needed.

**Comment by fbraad** [comment]
This is exactly what im trying to do as well, but im missing the timestamp in my mqtt data. Any chance you can share the yaml on the mqtt sensor you created as well?
Thanks!

**Reply by chunkysteveo** [reply]
Do you have the Time to Ready sensor coming into HA, which is a sensor in "hours" value?

My "Timestamp sensor" was just a template sensor, using the above code I shared. (although I need to work on the template a little more, as it says it's ready "next year", once the time for ready has passed).

**Reply by fbraad** [reply]
I only have sensor.layzspa_time_to_ready as a text sensor. I cannot see any time attributes on it and sensor.layzspa_time_to_ready_time says unknown.  - I havent messed with the MQTT settings at all - just configured MQTT on the board running the latest general build. -so i guessed that you might have templated a sensor yourself... But ill keep digging. :)

**Reply by chunkysteveo** [reply]
Ahh yes. The current firmware doesn't have the hours value as a sensor in MQTT, but the dev version does. I created my own custom MQTT sensor in Home Assistant to extract the hours value as a sensor. And then I created a template sensor to turn that hour(s) value into a future timestamp....

I added this in my configuration to add the missing sensor (which will need to be removed when the new firmware has it):
```
mqtt:
  sensor:
    - name: "Layzspa Time To Ready Time"
      unique_id: "layzspa_time_to_ready_timeYOUR_LAYZSPA_MQTT_ID"
      value_template: '{{ value_json.T2R }}'
      payload_not_available: Dead
      availability_topic: layzspa/Status
      state_topic: layzspa/times
      payload_available: Alive
      icon: mdi:clock
      expire_after: 700
      unit_of_measurement: "Hours"
      device:
        configuration_url: http://192.168.1.YOUR_IP
        connections:
          - - mac
            - A1:B2:C3:D4:E5:F6
        identifiers: 'YOUR_LAYZSPA_MQTT_ID'
        manufacturer: Visualapproach
        model: MIAMI2021
        sw_version: 2024-06-17-1334
        name: layzspa
```
And I then created a template sensor in helpers called "Time To Ready Timestamp", with a device class of "Timestamp", and the state template as:
```
{{ (
(now() + timedelta(weeks=52)) | as_datetime | as_local
if
            states('sensor.layzspa_layzspa_time_to_ready_time')
            | float < 0 
            else
            (now() + timedelta(hours=states('sensor.layzspa_layzspa_time_to_ready_time') | float)) | as_datetime | as_local)
            
}}
```
![image](https://github.com/user-attachments/assets/f4fab995-0f19-4503-9bbe-f04669409146)

Associated it with the layzspa device, and hey-presto - the HA frontend naturally converts any future times into human readable time scales. As I said before, I want to change it, as it says "Next Year", when the temp has reached, where as it should check for the heating states also - but that's for another day!

Let me know if that helps!?

**Reply by fbraad** [reply]
Awesome. Just what i needed. Thank you.

I was aleady trying my luck with mqtt explorer and some trial-and-error templating, and ended up getting it to work with the following:

```
mqtt:
  - sensor:
      device:
        name: Layzspa
        identifiers: 'YOUR_LAYZSPA_MQTT_ID'
      state_topic: layzspa/times
      name: Layzspa Time To Ready Time
      unique_id: "layzspa_time_to_ready_timeYOUR_LAYZSPA_MQTT_ID"
      value_template: "{{ value_json.T2R }}"
      payload_not_available: Dead
      availability_topic: layzspa/Status
      payload_available: Alive
      icon: mdi:clock
      expire_after: 700
      unit_of_measurement: "Hours"
```

and your template helper. 

I have "next year" currently as well. But this will do fine for now. Ill update here if i end up refining it myself.
