### DISCUSSION TITLE
Help with new Dashboard

### DISCUSSION THREAD

**Discussion by cofik1976** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#841] [Q&A]
Hi,

Who can help me with how to make myself such a Dashboard that I saw in one of the discussions here.
![obraz](https://github.com/user-attachments/assets/1afba29d-e4cc-4f1d-9a0e-50e54a4049f5)

Where should I paste the code given in the post.... ?

![obraz](https://github.com/user-attachments/assets/91031f6e-16fd-4da6-bc45-2d92d9cef4ed)

I use Home Assistant 
Hacks.

I need step by step instructions.

**Comment by PossiblyMax** [comment]
Oh, I just did this, I can help you out!

## HACS
So first of all pop into HACS and search `Mushroom` and install it, and `mini-graph-card` and install that too.

## Extra MQTT Config
Now you'll need to edit the `configuration.yaml` file in home assistant. I have the Studio Code Server addon but you can use whichever you prefer, as long as you can change the file.

Once you're in configuration.yaml, look for `mqtt:` in the file. You'll find one of four things:
1. It won't be there. This is fine, use the whole next block
2. It will be something like `mqtt: !include ` and then another file name. This is also fine, but you will need to switch to the other file to paste the block, and leave off the first line
3. It will be `mqtt: {}`. This is still fine, remove the line and add the whole block
4. It will be `mqtt:` on it's own line, and below it some entries before the next section. This is all good, leave off the first line of the paste.

Paste this:
```yaml
mqtt:
  - name: "Layzspa Display"
    unique_id: "layzspa_display"
    state_topic: "layzspa/message"
    icon: mdi:fit-to-screen
    value_template: >-
      {% set ASCII = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx !x#$%&'()*+`-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz" %}
      {% set ch1=ASCII[value_json.CH1] %}
      {% set ch2=ASCII[value_json.CH2] %}
      {% set ch3=ASCII[value_json.CH3] %}
      {{ch1}}{{ch2}}{{ch3}}
    availability_topic: "layzspa/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"

```

## Dashboard
Ok now to add the display to the dashboard you want to configure. Note you can't edit the Overview, so if you don't have any dashboards then you'll need to pop into the Settings->Dashboard screen and `+ADD DASHBOARD` and set up a new dashboard from scratch, and navigate to the dashboard you created.

Click the Edit button on the dashboard (the pen icon in the top right) and then click the add section button to get a new section.
![image](https://github.com/user-attachments/assets/6631373e-e68f-40b0-ba3c-63de62c83355)

Here's where you get an option. Now the original post you screenshotted does it one way and I changed it to be slightly different, though it looks pretty similar.

### Option 1: My Dashboard
1. In the new section click the pen in the heading.
![image](https://github.com/user-attachments/assets/832c0647-96dd-46b3-b15f-a0847246adba)

2. Then click the three dots and choose Edit in Yaml
![image](https://github.com/user-attachments/assets/7afcde62-0086-4d41-9808-a094bda307bc)

3. Clear out the text in the box, paste this into the box instead:
```yaml
type: grid
cards:
  - type: heading
    heading_style: title
    badges:
      - type: entity
        entity: binary_sensor.layzspa_heater
      - type: entity
        show_state: true
        show_icon: true
        entity: binary_sensor.layzspa_ready
    heading: Hot Tub
    icon: mdi:hot-tub
  - type: custom:mushroom-entity-card
    entity: sensor.layzspa_display
    name: Hot Tub Display
    icon: mdi:fit-to-screen
    icon_color: disabled
    layout: horizontal
    fill_container: true
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
    grid_options:
      columns: 6
      rows: 1
  - type: custom:mushroom-template-card
    primary: Hot Tub Ready
    secondary: >-
      {%- if is_state('binary_sensor.layzspa_ready', 'off') %} {{
      states('sensor.layzspa_time_to_target') | round(1) }} Hours to target  {%
      else %} Time for a dip! {% endif %}
    icon: >-
      {%- if is_state('binary_sensor.layzspa_ready', 'off') %} mdi:thumb-down{%
      else %}mdi:thumb-up{% endif %}
    layout: horizontal
    entity: binary_sensor.layzspa_ready
    icon_color: >-
      {%- if is_state('binary_sensor.layzspa_ready', 'off') %} red {% else %}
      green {% endif %}
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
    grid_options:
      columns: 6
      rows: 1
  - square: false
    columns: 3
    type: grid
    cards:
      - type: custom:mushroom-entity-card
        entity: switch.layzspa_pump
        secondary_info: none
        name: Pump
        fill_container: true
        layout: vertical
        tap_action:
          action: toggle
      - type: custom:mushroom-entity-card
        entity: switch.layzspa_heat_regulation
        secondary_info: none
        layout: vertical
        fill_container: true
        tap_action:
          action: toggle
        name: Heater
      - type: custom:mushroom-entity-card
        entity: switch.layzspa_airbubbles
        secondary_info: none
        layout: vertical
        tap_action:
          action: toggle
        name: Bubbles
        fill_container: true
  - type: custom:mushroom-template-card
    primary: Filter Reset
    secondary: "Age: {{ states('sensor.layzspa_filter_age') | round(1) }} days"
    icon: >-
      {%- if states('sensor.layzspa_filter_age') | int > 10 %} mdi:sync {% else
      %} mdi:air-filter {% endif %}
    layout: horizontal
    entity: button.layzspa_reset_filter_change_timer
    hold_action:
      action: toggle
    tap_action:
      action: none
    fill_container: false
    icon_color: >-
      {%- if states('sensor.layzspa_filter_age') | int > 10 %} red {% else %}
      disabled {% endif %}
    grid_options:
      columns: 6
      rows: 1
  - type: custom:mushroom-template-card
    primary: Chlorine Reset
    secondary: "Age: {{ states('sensor.layzspa_chlorine_age') | round (1) }} days"
    icon: >-
      {%- if states('sensor.layzspa_chlorine_age') | int > 10 %} mdi:sync {%
      else %} mdi:test-tube {% endif %}
    entity: button.layzspa_reset_chlorine_timer
    layout: horizontal
    tap_action:
      action: none
    hold_action:
      action: toggle
    icon_color: >-
      {%- if states('sensor.layzspa_chlorine_age') | int > 10 %} red {% else %}
      disabled {% endif %}
    grid_options:
      columns: 6
      rows: 1
  - type: horizontal-stack
    cards:
      - type: tile
        entity: sensor.layzspa_target_temp_c
        features_position: bottom
        vertical: false
        name: Chill (25°)
        icon: mdi:thermometer-minus
        tap_action:
          action: perform-action
          perform_action: script.hottubboostmode
          target: {}
          data:
            mode: Chill
        color: cyan
        hide_state: true
      - type: gauge
        severity:
          green: 0
          yellow: 1200
          red: 1800
        max: 2000
        needle: true
        entity: sensor.layzspa_power
        layout_options:
          grid_columns: 1
          grid_rows: 2
        name: " "
      - type: tile
        entity: sensor.layzspa_target_temp_c
        features_position: bottom
        vertical: false
        name: Boost (38°)
        icon: mdi:thermometer-plus
        tap_action:
          action: perform-action
          perform_action: script.hottubboostmode
          target: {}
          data:
            mode: Boost
        color: green
        hide_state: true
  - type: thermostat
    entity: climate.layzspa_temperature_control
    name: Hot Tub
    grid_options:
      columns: 6
      rows: 4
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        name: Hot Tub Temperature
        entities:
          - entity: sensor.layzspa_virtual_temp_c
            name: Virtual Temp
            color: "#FF1493"
            show_fill: false
            hours_to_show: 12
          - entity: sensor.layzspa_temp_c
            name: Pump Temp
            color: "#FF149350"
            show_fill: false
            hours_to_show: 12
          - entity: sensor.layzspa_target_temp_c
            name: Target Temp
            show_fill: false
            color: "#00BFFF"
            hours_to_show: 12
          - entity: weather.home
            attribute: temperature
            name: Ambient Temp
            show_fill: false
            color: "#44FF4440"
            hours_to_show: 12
        show:
          legend: false
          fill: null
        height: 148
        align_state: center
      - type: custom:mushroom-entity-card
        entity: sensor.layzspa_time_to_ready
        layout: horizontal
        name: Time to Target Temp
        fill_container: false
        icon_color: disabled
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
        icon: mdi:target
    grid_options:
      rows: 4
      columns: 6
```

4. Click save, and then Done on the dashboard.

Now this dashboard has a script to simplify boosting and chilling. Go into Settings -> Automations and scenes -> Scripts and `+ CREATE SCRIPT`. Switch to YAML mode and clear it out and paste this:
```yaml
sequence:
  - if:
      - condition: template
        value_template: "{{ (mode == 'Boost') }}"
    then:
      - action: climate.set_temperature
        metadata: {}
        data:
          temperature: 38
        target:
          entity_id: climate.layzspa_temperature_control
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - switch.layzspa_pump
            - switch.layzspa_heat_regulation
    else:
      - action: climate.set_temperature
        metadata: {}
        data:
          temperature: 25
        target:
          entity_id: climate.layzspa_temperature_control
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
            - switch.layzspa_heat_regulation
            - switch.layzspa_pump
fields:
  mode:
    selector:
      text: null
    name: Mode
    description: Specify 'Boost' to set to 38 or 'Chill' to go into chill mode
    required: true
    default: Boost
alias: Hot Tub Boost Mode
description: Boost the Hot Tub to 38 degrees or chill it down to 25
```

This will ensure the boost and chill buttons above work properly, and that should be everything!

This is the result:
![image](https://github.com/user-attachments/assets/af29e1a4-ebaf-4c0f-9fe8-f4d0008bbcb0)

The benefit of this is that the components are mostly separate so they're easier to move around or edit individually.

### Option 2: Original Post Dashboard

1. Click the Add Card button in the new section:
![image](https://github.com/user-attachments/assets/83f0db3f-d76b-4724-8c6b-22df205c9686)

2. Type 'manual' into the search box, and click the Manual card
![image](https://github.com/user-attachments/assets/37ec6104-abee-4b92-b512-a1a56578301a)

3. Clear out the text from the box and paste in the yaml below:
```yaml
type: vertical-stack
cards:
  - square: false
    columns: 2
    type: grid
    cards:
      - type: custom:mushroom-entity-card
        entity: sensor.layzspa_display
        name: Hot Tub Display
        icon: mdi:fit-to-screen
        icon_color: disabled
        layout: horizontal
        fill_container: true
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
      - type: custom:mushroom-template-card
        primary: Hot Tub Ready
        secondary: >-
          {%- if is_state('binary_sensor.layzspa_ready', 'off') %} {{
          states('sensor.layzspa_time_to_target') | round(1) }} Hours to target 
          {% else %} Time for a dip {{ user }} {% endif %}
        icon: >-
          {%- if is_state('binary_sensor.layzspa_ready', 'off') %}
          mdi:thumb-down{% else %}mdi:thumb-up{% endif %}
        layout: horizontal
        entity: binary_sensor.layzspa_ready
        icon_color: >-
          {%- if is_state('binary_sensor.layzspa_ready', 'off') %} red {% else
          %} green {% endif %}
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
  - square: false
    columns: 3
    type: grid
    cards:
      - type: custom:mushroom-entity-card
        entity: switch.layzspa_pump
        secondary_info: none
        name: Pump
        fill_container: true
        layout: vertical
        tap_action:
          action: toggle
      - type: custom:mushroom-entity-card
        entity: switch.layzspa_heat_regulation
        secondary_info: none
        layout: vertical
        fill_container: true
        tap_action:
          action: toggle
        name: Heater
      - type: custom:mushroom-entity-card
        entity: switch.layzspa_airbubbles
        secondary_info: none
        layout: vertical
        tap_action:
          action: toggle
        name: Bubbles
        fill_container: true
  - square: false
    columns: 2
    type: grid
    cards:
      - type: custom:mushroom-template-card
        primary: Filter Reset
        secondary: "Age: {{ states('sensor.layzspa_filter_age') | round(1) }} days"
        icon: >-
          {%- if states('sensor.layzspa_filter_age') | int > 10 %} mdi:sync {%
          else %} mdi:air-filter {% endif %}
        layout: horizontal
        entity: button.layzspa_reset_filter_change_timer
        hold_action:
          action: toggle
        tap_action:
          action: none
        fill_container: false
        icon_color: >-
          {%- if states('sensor.layzspa_filter_age') | int > 10 %} red {% else
          %} disabled {% endif %}
      - type: custom:mushroom-template-card
        primary: Chlorine Reset
        secondary: "Age: {{ states('sensor.layzspa_chlorine_age') | round (1) }} days"
        icon: >-
          {%- if states('sensor.layzspa_chlorine_age') | int > 10 %} mdi:sync {%
          else %} mdi:test-tube {% endif %}
        entity: button.layzspa_reset_chlorine_timer
        layout: horizontal
        tap_action:
          action: none
        hold_action:
          action: toggle
        icon_color: >-
          {%- if states('sensor.layzspa_chlorine_age') | int > 10 %} red {% else
          %} disabled {% endif %}
  - square: true
    columns: 2
    type: grid
    cards:
      - type: thermostat
        entity: climate.layzspa_temperature_control
        name: Hot Tub
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            name: Hot Tub Temperature
            entities:
              - entity: sensor.layzspa_temp_c
                name: Current
                color: "#FF1493"
                hours_to_show: 12
              - entity: sensor.layzspa_target_temp_c
                name: Target
                color: "#00BFFF"
                hours_to_show: 12
          - type: custom:mushroom-entity-card
            entity: sensor.layzspa_time_to_ready
            layout: horizontal
            name: Time to Target Temp
            fill_container: false
            icon_color: disabled
            tap_action:
              action: none
            hold_action:
              action: none
            double_tap_action:
              action: none
            icon: mdi:target
```

4. Click save, and then Done on the dashboard, and you should be done!

## Automation
I don't like to run the pump all the time as it can add up, but I do want to run it occasionally. For one, it helps correct the virtual temperature, and for another, it helps keep the pool clean! So I've made an automation that turns it on for 10 minutes every hour, unless the heater is on (meaning you are already running the pump).
The automation also syncs ambient weather using the weather service, to the pump. I believe this is necessary for the module to better calculate the virtual temperature!

```yaml
alias: Hot Tub - Pump and Ambient Temp
description: >-
  Turn on the pump for 10 minutes each hour. It will sync the virtual
  temperature and clean the pool a little.

  When the weather changes, set the ambient temp on the module.
triggers:
  - trigger: time_pattern
    hours: "*"
    minutes: "20"
    id: trigger_pump
  - entity_id:
      - weather.home
    attribute: temperature
    trigger: state
    id: set_ambient_temp
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - trigger_pump
          - condition: state
            entity_id: switch.layzspa_heat_regulation
            state: "off"
            for:
              hours: 0
              minutes: 20
              seconds: 0
        sequence:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.layzspa_pump
          - delay:
              hours: 0
              minutes: 10
              seconds: 0
              milliseconds: 0
          - if:
              - condition: state
                entity_id: switch.layzspa_heat_regulation
                state: "off"
            then:
              - action: switch.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id: switch.layzspa_pump
      - conditions:
          - condition: trigger
            id:
              - set_ambient_temp
          - condition: not
            conditions:
              - condition: state
                entity_id: weather.home
                state: unknown
              - condition: state
                entity_id: weather.home
                state: unavailable
        sequence:
          - action: number.set_value
            metadata: {}
            data:
              value: "{{state_attr('weather.home','temperature')|round}}"
            target:
              entity_id: number.layzspa_amb_temp_c
mode: parallel
max: 2
```

Hope that helps!
