### ISSUE TITLE
Integration directly to homeassistant (config)

### ISSUE THREAD

**Issue by strozl** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#135]
I don't use nodered in combination with home-assistant, so i integrated mqtt messages directly to home-assistant

configuration.yaml
```
sensor:
  - platform: mqtt
    name: spa button
    state_topic: "BW_2.0.0/button"
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
  - platform: mqtt
    name: spa connect count
    state_topic: "BW_2.0.0/MQTT_Connect_Count"

  - platform: mqtt
    name: spa temperature
    state_topic: "BW_2.0.0/message"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.TMP }}"
    expire_after: 600
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
  - platform: mqtt
    name: spa target temperature
    unit_of_measurement: '°C'
    state_topic: "BW_2.0.0/message"
    value_template: "{{ value_json.TGT }}"
    expire_after: 600

switch:
  - platform: mqtt
    command_topic: "BW_2.0.0/command"
    state_topic: "BW_2.0.0/message"
    value_template: |- #"{{ value_json.GRN }}"
      {% if value_json.RED == 1 %}
        1
      {% elif value_json.GRN == 1 %}
        1
      {% else %}
        0
      {% endif %}
    name: spa heater
    icon: mdi:radiator
    state_on: 1
    state_off: 0
    payload_on: '{CMD:3,VALUE:true,XTIME:0,INTERVAL:0}'
    payload_off: '{CMD:3,VALUE:false,XTIME:0,INTERVAL:0}'
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
  - platform: mqtt
    command_topic: "BW_2.0.0/command"
    state_topic: "BW_2.0.0/message"
    value_template: "{{ value_json.AIR }}"
    name: spa airbubbles
    icon: mdi:chart-bubble
    payload_on: '{CMD:2,VALUE:true,XTIME:0,INTERVAL:0}'
    payload_off: '{CMD:2,VALUE:false,XTIME:0,INTERVAL:0}'
    state_on: 1
    state_off: 0
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
  - platform: mqtt
    command_topic: "BW_2.0.0/command"
    state_topic: "BW_2.0.0/message"
    value_template: "{{ value_json.FLT }}"
    name: spa pump
    icon: mdi:pump
    payload_on: '{CMD:4,VALUE:true,XTIME:0,INTERVAL:0}'
    payload_off: '{CMD:4,VALUE:false,XTIME:0,INTERVAL:0}'
    state_on: 1
    state_off: 0
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"

  - platform: mqtt
    command_topic: "BW_2.0.0/command"
    state_topic: "BW_2.0.0/message"
    value_template: "{{ value_json.UNT }}"
    name: spa temperature unit
    icon: mdi:temperature-celsius
    payload_on: '{CMD:1,VALUE:true,XTIME:0,INTERVAL:0}'
    payload_off: '{CMD:1,VALUE:false,XTIME:0,INTERVAL:0}'
    state_on: 1
    state_off: 0
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
binary_sensor:
  - platform: mqtt
    name: spa lock
    state_topic: "BW_2.0.0/message"
    value_template: |- #"{{ value_json.LCK }}"
      {% if value_json.LCK == 1 %}
        OFF
      {% else %}
        ON
      {% endif %}
    expire_after: 600
    icon: mdi:lock
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
    device_class: lock

  - platform: mqtt
    name: spa heating
    state_topic: "BW_2.0.0/message"
    value_template: |- #"{{ value_json.RED }}"
      {% if value_json.RED == 1 %}
        ON
      {% else %}
        OFF
      {% endif %}
    icon: mdi:fire
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
    expire_after: 600
  - platform: mqtt
    name: spa ready
    state_topic: "BW_2.0.0/message"
    value_template: |- #"{{ value_json.RED }}"
      {% if value_json.TMP > 30 %}
        {% if value_json.TMP >= value_json.TGT-1 %}
          ON
        {% else %}
          OFF
        {% endif %}

      {% else %}
        OFF
      {% endif %}
    icon: mdi:hot-tub
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
    expire_after: 600
  - platform: mqtt
    name: spa power
    device_class: power
    state_topic: "BW_2.0.0/message"
    value_template: |- #"{{ value_json.RED }}"
      {% if value_json.PWR == 1 %}
        ON
      {% else %}
        OFF
      {% endif %}
    availability_topic: "BW_2.0.0/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"
    expire_after: 600
```

automations.yaml
```
- id: '1634672047071'
  alias: Spa target (from spa)
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.spa_target_temperature
  condition: []
  action:
  - service: input_number.set_value
    data:
      entity_id: input_number.spa_target_temp
      value: '{{states(''sensor.spa_target_temperature'')}}'
  mode: single
- id: '1634672260932'
  alias: Spa target (to spa)
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.spa_target_temp
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: BW_2.0.0/command
      payload_template: '{CMD:0,VALUE:{{states(''input_number.spa_target_temp'')|int}},XTIME:0,INTERVAL:0}'
  mode: single
```

you need to add helper input_number with name spa_target_temp 
```
input_number:
  spa_target_temp:
    name: SPA Target Temperature
    min: 20
    max: 40
    step: 1
```

If you don't send messages to the default topic prefix, adjust it.
